import { useState } from "react";
import { describe, expect, it } from "vitest";
import { createBook, createBookList, type Book } from "@/test/utils/factories/book.factory";
import { renderWithProviders, screen, userEvent } from "@/test/utils/render";

function BookCard({ book }: { book: Book }) {
  const [reserved, setReserved] = useState(false);

  return (
    <article aria-label={book.title}>
      <h2>{book.title}</h2>
      <p>{book.author}</p>
      <button type="button" onClick={() => setReserved(true)} disabled={reserved}>
        {reserved ? "Reserved" : "Reserve"}
      </button>
    </article>
  );
}

function BookShelf({ books }: { books: Book[] }) {
  return (
    <section aria-label="Catalog">
      {books.length === 0 ? (
        <p>No volumes have been cataloged yet.</p>
      ) : (
        <ul>
          {books.map((book) => (
            <li key={book._id}>
              <BookCard book={book} />
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

describe("component example", () => {
  it("renders a list of books generated by the data factory", () => {
    const books = createBookList(2, { genre: "Science Fiction" });
    books[0] = { ...books[0], author: "Ada Lovelace" };

    renderWithProviders(<BookShelf books={books} />);

    expect(screen.getByRole("heading", { name: books[0].title })).toBeInTheDocument();
    expect(screen.getByText(books[1].author)).toBeInTheDocument();
    expect(screen.getAllByRole("listitem")).toHaveLength(2);
  });

  it("updates UI in response to user interactions", async () => {
    const book = createBook();

    renderWithProviders(<BookShelf books={[book]} />);
    const reserveButton = screen.getByRole("button", { name: "Reserve" });

    await userEvent.click(reserveButton);

    expect(screen.getByRole("button", { name: "Reserved" })).toBeDisabled();
  });

  it("renders a literary empty state instead of an empty list", () => {
    renderWithProviders(<BookShelf books={[]} />);

    expect(screen.getByText("No volumes have been cataloged yet.")).toBeInTheDocument();
    expect(screen.queryByRole("list")).not.toBeInTheDocument();
  });

  it("exposes accessible semantics for assistive technology", () => {
    const book = createBook({ title: "The Accessible Grimoire" });

    renderWithProviders(<BookShelf books={[book]} />);

    expect(screen.getByRole("region", { name: "Catalog" })).toBeInTheDocument();
    expect(screen.getByRole("article", { name: book.title })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Reserve" })).toBeInTheDocument();
  });
});
