// This file is auto-generated by scripts/contract/extract.ts
// Do not edit manually. Run `npm run contract:extract` to regenerate.

export interface EndpointParameter {
  name: string;
  in: 'path' | 'query';
  required?: boolean;
  schema: { type: string; minimum?: number; maximum?: number; enum?: string[] };
}

export interface EndpointDefinition {
  method: string;
  path: string;
  summary: string;
  parameters: EndpointParameter[];
  requestBody?: { required: boolean; ref: string };
  responses: Record<string, { description: string; ref?: string }>;
}

export const ENDPOINTS: EndpointDefinition[] = [
  {
    method: "GET",
    path: "/books",
    summary: "List books with optional filters and pagination",
    parameters: [
          {
                "name": "genre",
                "in": "query",
                "schema": {
                      "type": "string"
                }
          },
          {
                "name": "author",
                "in": "query",
                "schema": {
                      "type": "string"
                }
          },
          {
                "name": "title",
                "in": "query",
                "schema": {
                      "type": "string"
                }
          },
          {
                "name": "page",
                "in": "query",
                "schema": {
                      "type": "integer",
                      "minimum": 1
                }
          },
          {
                "name": "limit",
                "in": "query",
                "schema": {
                      "type": "integer",
                      "minimum": 1,
                      "maximum": 100
                }
          }
    ],
    responses: {
          "200": {
                "description": "Paginated list of books"
          },
          "400": {
                "ref": "#/components/responses/ValidationError"
          },
          "500": {
                "ref": "#/components/responses/InternalError"
          }
    },
  },
  {
    method: "POST",
    path: "/books",
    summary: "Create a new book",
    parameters: [],
    requestBody: {"required":true,"ref":"#/components/schemas/CreateBookDto"},
    responses: {
          "201": {
                "description": "Book created successfully"
          },
          "400": {
                "ref": "#/components/responses/ValidationError"
          },
          "409": {
                "ref": "#/components/responses/ConflictError"
          },
          "500": {
                "ref": "#/components/responses/InternalError"
          }
    },
  },
  {
    method: "GET",
    path: "/books/{id}",
    summary: "Get a book by id",
    parameters: [
          {
                "name": "id",
                "in": "path",
                "required": true,
                "schema": {
                      "type": "string"
                }
          }
    ],
    responses: {
          "200": {
                "description": "Book found"
          },
          "400": {
                "ref": "#/components/responses/ValidationError"
          },
          "404": {
                "ref": "#/components/responses/NotFoundError"
          },
          "500": {
                "ref": "#/components/responses/InternalError"
          }
    },
  },
  {
    method: "PATCH",
    path: "/books/{id}",
    summary: "Partially update a book",
    parameters: [
          {
                "name": "id",
                "in": "path",
                "required": true,
                "schema": {
                      "type": "string"
                }
          }
    ],
    requestBody: {"required":true,"ref":"#/components/schemas/UpdateBookDto"},
    responses: {
          "200": {
                "description": "Book updated successfully"
          },
          "400": {
                "ref": "#/components/responses/ValidationError"
          },
          "404": {
                "ref": "#/components/responses/NotFoundError"
          },
          "409": {
                "ref": "#/components/responses/ConflictError"
          },
          "500": {
                "ref": "#/components/responses/InternalError"
          }
    },
  },
  {
    method: "DELETE",
    path: "/books/{id}",
    summary: "Delete a book",
    parameters: [
          {
                "name": "id",
                "in": "path",
                "required": true,
                "schema": {
                      "type": "string"
                }
          }
    ],
    responses: {
          "204": {
                "description": "Book deleted successfully"
          },
          "400": {
                "ref": "#/components/responses/ValidationError"
          },
          "404": {
                "ref": "#/components/responses/NotFoundError"
          },
          "500": {
                "ref": "#/components/responses/InternalError"
          }
    },
  },
];
