// This file is auto-generated by scripts/contract/extract.ts
// Do not edit manually. Run `npm run contract:extract` to regenerate.

export type Genre = "Romance" | "Thriller" | "Fantasy" | "Science Fiction" | "Dystopia" | "Historical Fiction" | "Adventure" | "Self Help" | "Popular Science" | "Horror" | "Young Adult" | "Children" | "Health" | "Sports" | "Cooking";

export interface Book {
  _id: string;
  title: string;
  author: string;
  genre: "Romance" | "Thriller" | "Fantasy" | "Science Fiction" | "Dystopia" | "Historical Fiction" | "Adventure" | "Self Help" | "Popular Science" | "Horror" | "Young Adult" | "Children" | "Health" | "Sports" | "Cooking";
  synopsis: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateBookDto {
  title: string;
  author: string;
  genre: "Romance" | "Thriller" | "Fantasy" | "Science Fiction" | "Dystopia" | "Historical Fiction" | "Adventure" | "Self Help" | "Popular Science" | "Horror" | "Young Adult" | "Children" | "Health" | "Sports" | "Cooking";
  synopsis: string;
}

export interface UpdateBookDto {
  title?: string;
  author?: string;
  genre?: "Romance" | "Thriller" | "Fantasy" | "Science Fiction" | "Dystopia" | "Historical Fiction" | "Adventure" | "Self Help" | "Popular Science" | "Horror" | "Young Adult" | "Children" | "Health" | "Sports" | "Cooking";
  synopsis?: string;
}

export interface BookQueryDto {
  genre?: "Romance" | "Thriller" | "Fantasy" | "Science Fiction" | "Dystopia" | "Historical Fiction" | "Adventure" | "Self Help" | "Popular Science" | "Horror" | "Young Adult" | "Children" | "Health" | "Sports" | "Cooking";
  author?: string;
  title?: string;
  page?: number;
  limit?: number;
}

export interface PaginatedResponse {
  data: { _id: string; title: string; author: string; genre: "Romance" | "Thriller" | "Fantasy" | "Science Fiction" | "Dystopia" | "Historical Fiction" | "Adventure" | "Self Help" | "Popular Science" | "Horror" | "Young Adult" | "Children" | "Health" | "Sports" | "Cooking"; synopsis: string; createdAt: string; updatedAt: string }[];
  pagination: { page: number; limit: number; total: number; totalPages: number };
}

export interface ErrorResponse {
  message: string;
  code: string;
  details?: unknown;
}
