import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const OPENAPI_PATH = resolve(__dirname, "openapi.json");
const OUTPUT_DIR = resolve(__dirname, "../../frontend/src/test/contract");

interface OpenAPISchema {
  type?: string;
  required?: string[];
  properties?: Record<string, OpenAPISchema | { $ref: string }>;
  items?: OpenAPISchema | { $ref: string };
  enum?: string[];
  minimum?: number;
  maximum?: number;
  default?: unknown;
  description?: string;
  format?: string;
  additionalProperties?: OpenAPISchema | { $ref: string };
}

interface OpenAPISpec {
  components: {
    schemas: Record<string, OpenAPISchema>;
  };
  paths: Record<string, Record<string, OpenAPIEndpoint>>;
}

interface OpenAPIEndpoint {
  summary: string;
  parameters?: Array<{
    name: string;
    in: string;
    required?: boolean;
    schema: OpenAPISchema;
    description?: string;
  }>;
  requestBody?: {
    required: boolean;
    content: {
      "application/json": {
        schema: { $ref: string };
      };
    };
  };
  responses: Record<string, { description: string; $ref?: string } | { description: string }>;
}

function resolveRef(ref: string, spec: OpenAPISpec): OpenAPISchema {
  const path = ref.replace("#/", "").split("/");
  let current: unknown = spec;
  for (const segment of path) {
    current = (current as Record<string, unknown>)[segment];
  }
  return current as OpenAPISchema;
}

function schemaToTypeScript(
  name: string,
  schema: OpenAPISchema,
  spec: OpenAPISpec,
  indent = 0,
): string {
  const pad = "  ".repeat(indent);

  if (schema.$ref) {
    const resolved = resolveRef(schema.$ref, spec);
    return schemaToTypeScript(name, resolved, spec, indent);
  }

  if (schema.enum) {
    return `${pad}export type ${name} = ${schema.enum.map((v) => `"${v}"`).join(" | ")};\n`;
  }

  if (schema.type === "object" && schema.properties) {
    const lines: string[] = [`${pad}export interface ${name} {`];
    for (const [propName, propSchema] of Object.entries(schema.properties)) {
      const isRequired = schema.required?.includes(propName) ?? false;
      const propRef = propSchema as OpenAPISchema | { $ref: string };
      let typeStr: string;

      if ("$ref" in propRef) {
        const resolved = resolveRef(propRef.$ref, spec);
        typeStr = getInlineType(resolved, spec);
      } else {
        typeStr = getInlineType(propRef, spec);
      }

      lines.push(`${pad}  ${propName}${isRequired ? "" : "?"}: ${typeStr};`);
    }
    lines.push(`${pad}}\n`);
    return lines.join("\n");
  }

  if (schema.type === "array" && schema.items) {
    const itemsRef = schema.items as OpenAPISchema | { $ref: string };
    let itemType: string;
    if ("$ref" in itemsRef) {
      const resolved = resolveRef(itemsRef.$ref, spec);
      itemType = getInlineType(resolved, spec);
    } else {
      itemType = getInlineType(itemsRef, spec);
    }
    return `${itemType}[]`;
  }

  return "unknown";
}

function getInlineType(schema: OpenAPISchema | { $ref: string }, spec: OpenAPISpec): string {
  if ("$ref" in schema) {
    const resolved = resolveRef(schema.$ref, spec);
    return getInlineType(resolved, spec);
  }

  if (schema.enum) {
    return schema.enum.map((v) => `"${v}"`).join(" | ");
  }

  if (schema.type === "string") return "string";
  if (schema.type === "integer" || schema.type === "number") return "number";
  if (schema.type === "boolean") return "boolean";

  if (schema.type === "object" && schema.properties) {
    const entries = Object.entries(schema.properties)
      .map(([key, propSchema]) => {
        const propRef = propSchema as OpenAPISchema | { $ref: string };
        const typeStr = " $ref" in propRef
          ? getInlineType(resolveRef(propRef.$ref, spec), spec)
          : getInlineType(propRef as OpenAPISchema, spec);
        const isRequired = schema.required?.includes(key) ?? false;
        return `${key}${isRequired ? "" : "?"}: ${typeStr}`;
      })
      .join("; ");
    return `{ ${entries} }`;
  }

  if (schema.type === "array" && schema.items) {
    const itemsRef = schema.items as OpenAPISchema | { $ref: string };
    const itemType = "$ref" in itemsRef
      ? getInlineType(resolveRef(itemsRef.$ref, spec), spec)
      : getInlineType(itemsRef as OpenAPISchema, spec);
    return `${itemType}[]`;
  }

  return "unknown";
}

function generateTypes(spec: OpenAPISpec): string {
  const lines: string[] = [
    "// This file is auto-generated by scripts/contract/extract.ts",
    "// Do not edit manually. Run `npm run contract:extract` to regenerate.",
    "",
  ];

  for (const [name, schema] of Object.entries(spec.components.schemas)) {
    lines.push(schemaToTypeScript(name, schema, spec));
  }

  return lines.join("\n");
}

function generateEndpoints(spec: OpenAPISpec): string {
  const lines: string[] = [
    "// This file is auto-generated by scripts/contract/extract.ts",
    "// Do not edit manually. Run `npm run contract:extract` to regenerate.",
    "",
    "export interface EndpointParameter {",
    "  name: string;",
    "  in: 'path' | 'query';",
    "  required?: boolean;",
    "  schema: { type: string; minimum?: number; maximum?: number; enum?: string[] };",
    "}",
    "",
    "export interface EndpointDefinition {",
    "  method: string;",
    "  path: string;",
    "  summary: string;",
    "  parameters: EndpointParameter[];",
    "  requestBody?: { required: boolean; ref: string };",
    "  responses: Record<string, { description: string; ref?: string }>;",
    "}",
    "",
    "export const ENDPOINTS: EndpointDefinition[] = [",
  ];

  for (const [path, methods] of Object.entries(spec.paths)) {
    for (const [method, endpoint] of Object.entries(methods)) {
      const parameters = (endpoint.parameters ?? []).map((p) => ({
        name: p.name,
        in: p.in,
        required: p.required,
        schema: {
          type: p.schema.type ?? "string",
          ...(p.schema.minimum !== undefined && { minimum: p.schema.minimum }),
          ...(p.schema.maximum !== undefined && { maximum: p.schema.maximum }),
          ...(p.schema.enum && { enum: p.schema.enum }),
        },
      }));

      const requestBody = endpoint.requestBody
        ? { required: endpoint.requestBody.required, ref: endpoint.requestBody.content["application/json"].schema.$ref }
        : undefined;

      const responses: Record<string, { description: string; ref?: string }> = {};
      for (const [status, resp] of Object.entries(endpoint.responses)) {
        if ("$ref" in resp) {
          const resolved = resolveRef(resp.$ref, spec) as { description?: string };
          responses[status] = {
            description: resolved.description ?? resp.$ref.split("/").pop() ?? "",
            ref: resp.$ref,
          };
        } else {
          responses[status] = {
            description: resp.description,
          };
        }
      }

      lines.push("  {");
      lines.push(`    method: "${method.toUpperCase()}",`);
      lines.push(`    path: "${path}",`);
      lines.push(`    summary: "${endpoint.summary}",`);
      lines.push(`    parameters: ${JSON.stringify(parameters, null, 6).replace(/\n/g, "\n    ")},`);
      if (requestBody) {
        lines.push(`    requestBody: ${JSON.stringify(requestBody)},`);
      }
      lines.push(`    responses: ${JSON.stringify(responses, null, 6).replace(/\n/g, "\n    ")},`);
      lines.push("  },");
    }
  }

  lines.push("];\n");
  return lines.join("\n");
}

function main() {
  const spec: OpenAPISpec = JSON.parse(readFileSync(OPENAPI_PATH, "utf-8"));

  const types = generateTypes(spec);
  writeFileSync(resolve(OUTPUT_DIR, "openapi-types.ts"), types);
  console.log("Generated openapi-types.ts");

  const endpoints = generateEndpoints(spec);
  writeFileSync(resolve(OUTPUT_DIR, "endpoints.ts"), endpoints);
  console.log("Generated endpoints.ts");
}

main();
